#!/usr/bin/env bash
set -euo pipefail

# Color Reset
Color_Off=''

# Regular Colors
Red=''
Green=''
Blue=''

# Bold
Bold_White=''

if [[ -t 1 ]]; then
    # Reset
    Color_Off='\033[0m' # Text Reset

    # Regular Colors
    Red='\033[0;31m'
    Green='\033[0;32m'
    Blue='\033[0;34m'

    # Bold
    Bold_White='\033[1m' # Bold White
fi

error() {
    echo -e "${Red}ERROR:${Color_Off}\t$*" >&2
    exit 1
}

info() {
    echo -e "${Blue}INFO:${Color_Off}\t$*"
}

bold() {
    echo -e "\t${Bold_White}$* ${Color_Off}"
}

success() {
    echo -e "${Green}\xE2\x9C\x94\t$* ${Color_Off}"
}

repeat() {
    local start=1
    local end=${1:-80}
    local str="${2:-=}"
    local range=$(seq "$start" "$end")

    for _ in $range; do
        echo -n "$str"
    done
    echo
}

tildify() {
    if [[ $1 = $HOME/* ]]; then
        local replacement=\~

        echo "${1/$HOME/$replacement}"
    else
        echo "$1"
    fi
}

command -v sleep >/dev/null || error "Need to have sleep commend."
command -v pmset >/dev/null || error "Need to have pmset commend."

bin_url=https://raw.githubusercontent.com/mrbing47/slp/main/slp

install_dir=$HOME/.slp

bin=$install_dir/slp

if [[ ! -d $install_dir ]]; then
    mkdir -p "$install_dir" ||
        error "Failed to create install directory \"$install_dir\""
fi

info "Downloading the script"

curl -fsL --output "$bin" "$bin_url" ||
    error "Failed to download slp from \"$bin_url\""

chmod +x "$bin" ||
    error 'Failed to set permissions on slp executable'

echo
success "Successfully installed slp"

echo
info "Setting up the PATH"

case $(basename "$SHELL") in
fish)

    commands=(
        "set --export PATH $install_dir \$PATH"
    )

    fish_config=$HOME/.config/fish/config.fish
    tilde_fish_config=$(tildify "$fish_config")

    if [[ -w $fish_config ]]; then
        {
            repeat 50 "#"
            echo -e "##\tslp"

            for command in "${commands[@]}"; do
                echo "$command"
            done

            repeat 50 "#"
            echo
        } >>"$fish_config"

        info "Added \"$(tildify "$install_dir")\" to \$PATH in \"$tilde_fish_config\""

        refresh_command="source $tilde_fish_config"
    else
        echo "Manually add the directory to $tilde_fish_config (or similar):"

        for command in "${commands[@]}"; do
            bold "  $command"
        done
    fi
    ;;
zsh)

    commands=(
        "export PATH=\"$install_dir:\$PATH\""
    )

    zsh_config=$HOME/.zshrc
    tilde_zsh_config=$(tildify "$zsh_config")

    if [[ -w $zsh_config ]]; then
        {
            repeat 50 "#"
            echo -e "##\tslp"

            for command in "${commands[@]}"; do
                echo "$command"
            done

            repeat 50 "#"
            echo
        } >>"$zsh_config"

        info "Added \"$(tildify "$install_dir")\" to \$PATH in \"$tilde_zsh_config\""

        refresh_command="exec $SHELL"
    else
        echo "Manually add the directory to $tilde_zsh_config (or similar):"

        for command in "${commands[@]}"; do
            bold "  $command"
        done
    fi
    ;;
bash)

    commands=(
        "export PATH=$install_dir:\$PATH"
    )

    bash_configs=(
        "$HOME/.bashrc"
        "$HOME/.bash_profile"
    )

    if [[ ${XDG_CONFIG_HOME:-} ]]; then
        bash_configs+=(
            "$XDG_CONFIG_HOME/.bash_profile"
            "$XDG_CONFIG_HOME/.bashrc"
            "$XDG_CONFIG_HOME/bash_profile"
            "$XDG_CONFIG_HOME/bashrc"
        )
    fi

    set_manually=true
    for bash_config in "${bash_configs[@]}"; do
        tilde_bash_config=$(tildify "$bash_config")

        if [[ -w $bash_config ]]; then
            {
                repeat 50 "#"
                echo -e "##\tslp"

                for command in "${commands[@]}"; do
                    echo "$command"
                done

                repeat 50 "#"
                echo
            } >>"$bash_config"

            info "Added \"$(tildify "$install_dir")\" to \$PATH in \"$tilde_bash_config\""

            refresh_command="source $bash_config"
            set_manually=false
            break
        fi
    done

    if [[ $set_manually = true ]]; then
        echo "Manually add the directory to $tilde_bash_config (or similar):"

        for command in "${commands[@]}"; do
            bold "  $command"
        done
    fi
    ;;
*)
    echo 'Manually add the directory to ~/.bashrc (or similar):'
    bold "  export PATH=\"$install_dir:\$PATH\""
    ;;
esac

echo

if [[ $refresh_command ]]; then
    info "To get started, run:"
    bold "$refresh_command"
else
    bold "Restart the terminal to take effect"
fi

exit 0
